package billingexpr

import (
	"math"

	"github.com/expr-lang/expr/ast"
	"github.com/expr-lang/expr/parser"
)

// TierUnitPrices is the per-million-token price snapshot extracted from a
// standard tiered billing expression.
type TierUnitPrices struct {
	Input        float64
	Output       float64
	CacheRead    float64
	CacheWrite   float64
	CacheWrite1h float64
	UsedVars     map[string]bool
}

var supportedTierPriceVars = map[string]bool{
	"p":    true,
	"c":    true,
	"cr":   true,
	"cc":   true,
	"cc1h": true,
}

// ExtractTierUnitPrices returns prices only for the standard linear tier
// shape generated by the pricing UI. Custom expressions are intentionally
// rejected so billing reports never present guessed unit prices.
func ExtractTierUnitPrices(exprStr string, matchedTier string) (TierUnitPrices, bool) {
	if exprStr == "" || matchedTier == "" {
		return TierUnitPrices{}, false
	}
	_, body := ParseExprVersion(exprStr)
	tree, err := parser.Parse(body)
	if err != nil || tree == nil || tree.Node == nil {
		return TierUnitPrices{}, false
	}

	cost, found, ambiguous := findMatchedTierCost(tree.Node, matchedTier, nil)
	if !found || ambiguous {
		return TierUnitPrices{}, false
	}
	coefficients := make(map[string]float64)
	if !collectLinearTierTerms(cost, 1, coefficients) {
		return TierUnitPrices{}, false
	}
	for name, value := range coefficients {
		if name == "" {
			continue
		}
		if !supportedTierPriceVars[name] || math.IsNaN(value) || math.IsInf(value, 0) || value < 0 {
			return TierUnitPrices{}, false
		}
	}
	usedVars := make(map[string]bool, len(coefficients))
	for name := range coefficients {
		if name != "" {
			usedVars[name] = true
		}
	}
	return TierUnitPrices{
		Input:        coefficients["p"],
		Output:       coefficients["c"],
		CacheRead:    coefficients["cr"],
		CacheWrite:   coefficients["cc"],
		CacheWrite1h: coefficients["cc1h"],
		UsedVars:     usedVars,
	}, true
}

func findMatchedTierCost(node ast.Node, matchedTier string, current ast.Node) (ast.Node, bool, bool) {
	switch typed := node.(type) {
	case *ast.ConditionalNode:
		first, firstFound, firstAmbiguous := findMatchedTierCost(typed.Exp1, matchedTier, current)
		second, secondFound, secondAmbiguous := findMatchedTierCost(typed.Exp2, matchedTier, first)
		if firstAmbiguous || secondAmbiguous || (firstFound && secondFound) {
			return nil, false, true
		}
		if firstFound {
			return first, true, false
		}
		return second, secondFound, false
	case *ast.CallNode:
		callee, ok := typed.Callee.(*ast.IdentifierNode)
		if !ok || callee.Value != "tier" || len(typed.Arguments) != 2 {
			return nil, false, false
		}
		label, ok := typed.Arguments[0].(*ast.StringNode)
		if !ok || label.Value != matchedTier {
			return nil, false, false
		}
		if current != nil {
			return nil, false, true
		}
		return typed.Arguments[1], true, false
	default:
		return nil, false, false
	}
}

func collectLinearTierTerms(node ast.Node, multiplier float64, coefficients map[string]float64) bool {
	switch typed := node.(type) {
	case *ast.BinaryNode:
		switch typed.Operator {
		case "+":
			return collectLinearTierTerms(typed.Left, multiplier, coefficients) &&
				collectLinearTierTerms(typed.Right, multiplier, coefficients)
		case "-":
			return collectLinearTierTerms(typed.Left, multiplier, coefficients) &&
				collectLinearTierTerms(typed.Right, -multiplier, coefficients)
		case "*":
			if value, ok := tierNumericValue(typed.Left); ok {
				return collectLinearTierTerms(typed.Right, multiplier*value, coefficients)
			}
			if value, ok := tierNumericValue(typed.Right); ok {
				return collectLinearTierTerms(typed.Left, multiplier*value, coefficients)
			}
			return false
		default:
			return false
		}
	case *ast.IdentifierNode:
		coefficients[typed.Value] += multiplier
		return true
	case *ast.IntegerNode, *ast.FloatNode, *ast.UnaryNode:
		value, ok := tierNumericValue(node)
		if !ok {
			return false
		}
		// A constant is a valid reconciliation component, but it has no unit
		// price column and will remain in Other/Difference.
		coefficients[""] += multiplier * value
		return true
	default:
		return false
	}
}

func tierNumericValue(node ast.Node) (float64, bool) {
	switch typed := node.(type) {
	case *ast.IntegerNode:
		return float64(typed.Value), true
	case *ast.FloatNode:
		return typed.Value, true
	case *ast.UnaryNode:
		value, ok := tierNumericValue(typed.Node)
		if !ok {
			return 0, false
		}
		switch typed.Operator {
		case "+":
			return value, true
		case "-":
			return -value, true
		}
	}
	return 0, false
}
